# Generated by Django 5.1.4 on 2024-12-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=50, verbose_name='Name')),
                ('emobile', models.CharField(max_length=10, verbose_name='Mobile')),
                ('eemail', models.CharField(max_length=50, verbose_name='Email')),
                ('epassword', models.CharField(max_length=50, verbose_name='Password')),
                ('createAt', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
    ]
